Repository Team-Dasom/co-re-websites, pull requests merged in 2023-11, with the labels that each got.

#43 [REFACTOR/#42] Code 언어 변경 기능 -> 알고리즘 문제 해설 문제로 변경
  src/pages/ChangeCodeLanguagePage.js
  src/pages/SolveAlgorithmPage.js
  src/router.js
Labels: REFACTOR ♻️

#45 [FEAT/#44] 코드 리팩토링, 코드 주석 생성 기능 구현
  src/pages/AddCommentPage.js
  src/pages/RefactorCodePage.js
  src/store/addComment/addCommentSlice.js
  src/store/refactorCode/refactorCodeSlice.js
  src/store/store.js
Labels: FEAT ✨

#47 [MOD/#46] 입력 부분 숫자만 받을 수 있도록 변경 및 입력값에 '번' 붙이기
  src/components/conversation/Conversation.js
  src/pages/SolveAlgorithmPage.js
Labels: MOD ✅ 

#50 [MOD/#49] 컨텐츠 추천 기능 삭제
  src/components/RecommandContent/Content.js
  src/pages/RecommandContentPage.js
  src/router.js
Labels: MOD ✅ 

#53 [ADD/#52] 에러 처리 추가 코드 작성
  src/components/conversation/Conversation.js
  src/images/defaultProfileImage.jpg
  src/pages/AddCommentPage.js
  src/pages/RecommandVariableNamePage.js
  src/pages/RefactorCodePage.js
  src/pages/SolveAlgorithmPage.js
Labels: ADD ➕

#56 [MOD/#55] title, favicon 변경
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: MOD ✅ 

#57 [MOD] title, favicon 변경 main PR(#55)
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: MOD ✅ 

#59 [ADD/#58] GPT 바로가기 1차 구현
  src/components/Header/Header.js
Labels: ADD ➕

#62 [FEAT/#61] 로그아웃 기능 구현
  src/components/Login/KakaoRedirect.js
  src/pages/MyPage.js
Labels: FEAT ✨

#65 [FIX/#63] base url변경 및 로그인 유지
  src/components/Cookie/Cookies.js
  src/components/Header/Header.js
  src/components/Login/KakaoRedirect.js
  src/pages/MyPage.js
  src/store/KakaoLogin/kakaoUserSlice.js
Labels: FIX 🔨

#74 [UI/#73] 마이페이지 기능별 즐겨찾기 UI구현
  src/components/Bookmark/AddComentBookmark.js
  src/components/Bookmark/AlgorithmsBookmark.js
  src/components/Bookmark/RefactorBookmark.js
  src/components/Bookmark/VariableBookmark.js
  src/pages/Bookmark.js
  src/pages/MyPage.js
  src/router.js
Labels: UI 💄

#76 [FEAT/#75] 로그아웃 서버 요청 및 새로고침 시 유지
  package-lock.json
  package.json
  src/components/Header/Header.js
  src/components/Login/KakaoRedirect.js
  src/components/conversation/Conversation.js
  src/index.js
  src/pages/MyPage.js
  src/store/KakaoLogin/kakaoUserSlice.js
  src/store/store.js
Labels: FEAT ✨

#78 [UI/#77] 대화내용 즐겨찾기 UI 구현
  src/components/conversation/BookmarkBtn.js
  src/components/conversation/Conversation.js
  src/components/conversation/DeleteBtn.js
  src/images/DeleteBtn.svg
  src/images/OnBookmarkImg.svg
  src/images/defaultBookmarkImg.svg
Labels: UI 💄

#81 🔨 [FIX/#80] 콘솔 오류 해결
  src/App.js
  src/store/store.js
Labels: FIX 🔨

#83 [FEAT/#82] 복사 기능 구현
  src/components/conversation/BookmarkBtn.js
  src/components/conversation/CodeBlock.js
  src/components/conversation/CopyBtn.js
  src/components/conversation/DeleteBtn.js
  src/style/globals.css
Labels: FEAT ✨

#86 [HOTFIX/#85] 로컬에서만 복사되는 문제 해결
  package-lock.json
  package.json
  src/components/conversation/CopyBtn.js
Labels: HOTFIX 🚑️ 
