Repository Team-Dasom/co-re-websites, pull requests merged in 2023-10, with the labels that each got.

#2 [UI 💄/#1] 메인 페이지 구현
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Header.js
  src/components/StartPage.js
  src/images/logo-icon.png
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  src/style/globals.css
Labels: UI 💄

#4 💄 [UI/#3] 로그인 클릭시 로그인 모달 구현
  src/components/Header.js
  src/components/Login/LoginModal.js
  src/images/GithubLogin.svg
  src/images/KakaoLogin.svg
  src/images/LoginCoReLogo.svg
  src/images/LoginModalDelete.svg
Labels: UI 💄

#7 ✨ [FEAT/#5] 헤더 컴포넌트 연결
  package-lock.json
  package.json
  src/App.js
  src/components/Header.js
  src/components/Header/Header.js
  src/components/Header/HeaderText.js
  src/index.js
  src/routes/AddCommentPage.js
  src/routes/ChangeCodeLanguagePage.js
  src/routes/MainPage.js
  src/routes/RecommandContentPage.js
  src/routes/RecommandVariableNamePage.js
  src/routes/RefactorCodePage.js
  src/style/globals.css
Labels: FEAT ✨

#8 ✨ [FEAT/#6] 카카오 고결 로그인 구현
  .env
  package-lock.json
  package.json
  src/components/Login/KakaoRedirect.js
  src/components/Login/LoginModal.js
  src/index.js
Labels: FEAT ✨

#15 ✨ [FEAT/#13] 카카오 회원가입 서버랑 통신 완료
  package-lock.json
  package.json
  src/App.js
  src/components/Cookies.js
  src/components/Header/Header.js
  src/components/Login/KakaoRedirect.js
  src/index.js
Labels: FEAT ✨

#19 [UI/#18] 변수명 추천 UI구현
  src/images/gptImg.svg
  src/images/testImg.jpeg
  src/routes/RecommandVariableNamePage.js
Labels: UI 💄

#17 [FEAT/#16] 카카오 회원정보 저장
  src/App.js
  src/components/Header/Header.js
  src/components/Login/KakaoRedirect.js
  src/routes/MyPage.js
  src/store/KakaoLogin/kakaoUserSlice.js
  src/store/store.js
Labels: FEAT ✨

#22 ♻️ [REFACTOR/#21] router 별개로 분리해 관리
  jsconfig.json
  src/App.js
  src/components/Header/Header.js
  src/components/Header/HeaderText.js
  src/components/Login/KakaoRedirect.js
  src/components/Login/LoginModal.js
  src/hooks/useRouter.js
  src/index.js
  src/pages/AddCommentPage.js
  src/pages/ChangeCodeLanguagePage.js
  src/pages/MainPage.js
  src/pages/MyPage.js
  src/pages/RecommandContentPage.js
  src/pages/RecommandVariableNamePage.js
  src/pages/RefactorCodePage.js
  src/router.js
  src/store/store.js
  src/style/globals.css
Labels: REFACTOR ♻️

#28 [HOTFIX/#27] merge conflict 해결 후 파일 정리
  src/components/Login/KakaoRedirect.js
  src/pages/RecommandVariableNamePage.js
  src/routers/RecommandVariableNamePage.js
Labels: HOTFIX 🚑️ 

#30 [UI/#24] 드롭다운 컴포넌트 구현
  src/components/Dropdown.js
  src/pages/RecommandVariableNamePage.js
Labels: UI 💄

#32 [Feat/#31] Code 언어 변경 기능 구현
  package-lock.json
  package.json
  src/components/Dropdown.js
  src/components/conversation/Answer.js
  src/pages/ChangeCodeLanguagePage.js
  src/store/changeLanguage/changeLanguageSlice.js
  src/store/store.js
Labels: FEAT ✨

#33 [MOD/#29] 컨텐츠 추천 페이지 생성 및 유저 정보 쿠키에 저장
  src/components/Header/Header.js
  src/components/InputInPage.js
  src/components/Login/KakaoRedirect.js
  src/components/RecommandContent/Content.js
  src/components/VariableName/VariableName.js
  src/pages/MainPage.js
  src/pages/MyPage.js
  src/pages/RecommandContentPage.js
  src/pages/RecommandVariableNamePage.js
  src/store/KakaoLogin/statusSlice.js
  src/store/KakaoLogin/tokenSlice.js
  src/store/store.js
Labels: ADD ➕

#35 [FIX/#34] 변수명 추천 코드 수정
  src/components/InputInPage.js
  src/components/VariableName/InputDropDown.js
  src/pages/RecommandContentPage.js
  src/pages/RecommandVariableNamePage.js
  src/store/store.js
  src/store/variebleName/variebleNameSlice.js
Labels: FIX 🔨

#37 [FIX/#36] 언어 변경 기능 값 입력 후 엔터 누를 시 400 에러 발생 수정
  src/components/conversation/Conversation.js
  src/pages/ChangeCodeLanguagePage.js
Labels: FIX 🔨

#39 [FIX/#38] 변수명 추천 400에러 해결
  src/pages/RecommandVariableNamePage.js
Labels: FIX 🔨

#41 [Feat/#40] Pull Request 템플릿 제작
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/pull_request_template.md
Labels: FEAT ✨
